@include('vcard.parts.index'.$vcard->template.".".$vcard->session_page_order_1,[$vcard,$prefs])
@include('vcard.parts.index'.$vcard->template.".".$vcard->session_page_order_2,[$vcard,$prefs])
@include('vcard.parts.index'.$vcard->template.".".$vcard->session_page_order_3,[$vcard,$prefs])
@include('vcard.parts.index'.$vcard->template.".".$vcard->session_page_order_4,[$vcard,$prefs])          
@include('vcard.parts.index'.$vcard->template.".".$vcard->session_page_order_5,[$vcard,$prefs])    
@include('vcard.parts.index'.$vcard->template.".".$vcard->session_page_order_6,[$vcard,$prefs]) 
@include('vcard.parts.index'.$vcard->template.".".$vcard->session_page_order_7,[$vcard,$prefs])
@include('vcard.parts.index'.$vcard->template.".".$vcard->session_page_order_8,[$vcard,$prefs])  